name: Build Wasm Simd Image
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the image to build'
        required: true
        type: string

env:
   REGISTRY: ghcr.io
   ORG: cosmos
   IMAGE_NAME: ibc-go-wasm-simd
   GIT_TAG: "${{ inputs.tag }}"

jobs:
   build-image-at-tag:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
            ref: "${{ env.GIT_TAG }}"
            fetch-depth: 0
         - uses: actions/setup-python@v5
           with:
             python-version: '3.10'
         - name: Install dependencies
           run: make python-install-deps
         - name: Log in to the Container registry
           uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
           with:
              registry: ${{ env.REGISTRY }}
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
         - name: Build image
           run: | 
            # remove all `/` or `+` characters from the docker tag and replace them with a -.
            # this ensures the docker tag is valid.
            docker_tag="$(echo $GIT_TAG | sed 's/[^a-zA-Z0-9\.]/-/g')"
            make build-docker-wasm tag="${REGISTRY}/${ORG}/${IMAGE_NAME}:${docker_tag}"
            docker push "${REGISTRY}/${ORG}/${IMAGE_NAME}:${docker_tag}"
