name: Capability Module
# This workflow runs when a PR is opened that targets code that is part of the capability module.
on:
  pull_request:
    paths:
      - '.github/workflows/capability.yml'
      - 'modules/capability/**'
      - 'proto/capability/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-arch: ['amd64', 'arm', 'arm64']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build capability-module
        run: |
          cd modules/capability
          GOARCH=${{ matrix.go-arch }} go build ./...

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Go Test
        run: |
          cd modules/capability
          go test -v -mod=readonly ./...
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.53.1
          args: --timeout 5m
      - name: Lint
        run: |
          cd modules/capability
          golangci-lint run ./... -c ../../../.golangci.yml
