name: Compatibility E2E
on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the image to test'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  ORG: cosmos
  IMAGE_NAME: ibc-go-simd
#  GIT_TAG: '${{ inputs.tag }}'
  GIT_TAG: 'release/v5.0.x'

jobs:
  determine-docker-tag:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.set-docker-tag.outputs.docker-tag }}
    steps:
      - run: |
          docker_tag="$(echo $GIT_TAG | sed 's/\//-/')"
          echo $docker_tag
          echo "::set-output name=docker-tag::$docker_tag"
        id: set-docker-tag

  log-docker-tag:
    needs: determine-docker-tag
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.determine-docker-tag.outputs.docker-tag }}"

  load-test-matrix:
    outputs:
      test-matrix: ${{ steps.set-test-matrix.outputs.test-matrix }}
    needs: determine-docker-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          test_matrix="$(cat .github/compatibility-test-matrices/${{ needs.determine-docker-tag.outputs.docker-tag }}.json)"
          echo $test_matrix
          echo "::set-output name=test-matrix::$test_matrix"
        id: set-test-matrix

  e2e-tests:
    runs-on: ubuntu-latest
    needs: load-test-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.load-test-matrix.outputs.test-matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run e2e Test
        run: |
          cd e2e
          make e2e-test entrypoint=${{ matrix.entrypoint }} test=${{ matrix.test }}
        env:
          # each test has its own set of variables to specify which images are used.
          CHAIN_IMAGE: "${{ matrix.chain-image }}"
          CHAIN_A_TAG: "${{ matrix.chain-a-tag }}"
          CHAIN_B_TAG: "${{ matrix.chain-b-tag }}"
          CHAIN_BINARY: "${{ matrix.chain-binary }}"
          RLY_TAG: "v2.0.0"
