name: Tests / E2E Fork
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Local Container Registry
        run: docker run -d -p 5000:5000 --name registry-test registry:2
      - name: Docker Build & Push
        run: | 
          docker build . -t localhost:5000/ibc-go-simd-e2e:latest
          docker push localhost:5000/ibc-go-simd-e2e:latest

  # dynamically build a matrix of test/test suite pairs to run
  build-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - id: set-matrix
        run: echo "::set-output name=matrix::$(go run .github/scripts/build_test_matrix.go)"

  e2e:
    runs-on: ubuntu-latest
    needs:
      - build-test-matrix
      - docker-build
    env:
      SIMD_TAG: latest
      SIMD_IMAGE: localhost:5000/ibc-go-simd-e2e
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run e2e Test
        run: |
          cd e2e
          make e2e-test suite=${{ matrix.suite }} test=${{ matrix.test }}
