on:
  workflow_call:
    inputs:
      test-entry-point:
        description: 'Test entry point'
        required: true
        type: string
      chain-a-image:
        description: 'The image to use for chain A'
        required: true
        type: string
        default: "ghcr.io/cosmos/ibc-go-simd"
      chain-a-tag:
        description: 'The tag to use for chain A'
        required: true
        type: string
        default: main
      chain-b-image:
        description: 'The image to use for chain B'
        required: true
        type: string
        default: "ghcr.io/cosmos/ibc-go-simd"
      chain-b-tag:
        default: v4.0.0-rc3
        description: 'The tag to use for chain B'
        required: true
        type: string
      relayer-tag:
        description: 'The tag to use for the relayer'
        required: true
        default: "v2.0.0-rc2"
        type: string
      build-and-push-docker-image:
        description: "Flag to specify if the docker image should be built and pushed beforehand"
        required: false
        type: boolean
        default: false


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ibc-go-simd

jobs:
  docker-build:
    if: ${{ inputs.build-and-push-docker-image }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: ${{ env.REGISTRY }}/cosmos/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # dynamically build a matrix of test/test suite pairs to run
  build-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - id: set-matrix
        run: echo "::set-output name=matrix::$(go run cmd/build_test_matrix/main.go)"
        env:
          TEST_ENTRYPOINT: "${{ inputs.test-entry-point }}"

  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - build-test-matrix
      - docker-build
    env:
      CHAIN_A_SIMD_TAG: "${{ inputs.chain-a-tag }}"
      CHAIN_A_SIMD_IMAGE: "${{ inputs.chain-a-image }}"
      CHAIN_B_SIMD_TAG: "${{ inputs.chain-b-tag }}"
      CHAIN_B_SIMD_IMAGE: "${{ inputs.chain-b-image }}"
      RLY_TAG: "{{ inputs.relayer-tag }}"
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Run e2e Test
        run: |
          cd e2e
          make e2e-test suite=${{ matrix.suite }} test=${{ matrix.test }}
