name: Compatibility E2E (Release Branches)
on:
  - workflow_dispatch
  - push

env:
  REGISTRY: ghcr.io
  ORG: cosmos
  IMAGE_NAME: ibc-go-simd


jobs:
  build-release-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        release-branch:
          - release/v2.5.x
          - release/v3.4.x
          - release/v4.2.x
          - release/v5.0.x
          - release/v5.1.x
          - release/v6.0.x
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ matrix.release-branch }}"
          fetch-depth: 0
      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine docker tag
        run: |
          docker_tag="$(echo ${{ matrix.release-branch }} | sed 's/\//-/')"
          echo $docker_tag
          echo "::set-output name=docker-tag::$docker_tag"
        id: set-docker-tag
      - name: Fetch Makefile dependencies
        run: |
          mkdir -p contrib/devtools
          curl https://raw.githubusercontent.com/cosmos/ibc-go/main/contrib/devtools/Makefile -o contrib/devtools/Makefile
      - name: Fetch latest Dockerfile
        run: curl https://raw.githubusercontent.com/cosmos/ibc-go/main/Dockerfile -o Dockerfile
      - name: Build image
        run: |
          docker build . -t "${REGISTRY}/${ORG}/${IMAGE_NAME}:${{ steps.set-docker-tag.outputs.docker-tag }}"
          docker push "${REGISTRY}/${ORG}/${IMAGE_NAME}:${{ steps.set-docker-tag.outputs.docker-tag }}"

  transfer:
    needs:
      - build-release-images
    uses: ./.github/workflows/e2e-compatibility-workflow-call.yaml
    with:
      test-file-directory: "release-branches"
      test-suite: "transfer"

  client:
    needs:
      - build-release-images
    uses: ./.github/workflows/e2e-compatibility-workflow-call.yaml
    with:
      test-file-directory: "release-branches"
      test-suite: "client"

  incentivized-transfer:
    needs:
      - build-release-images
    uses: ./.github/workflows/e2e-compatibility-workflow-call.yaml
    with:
      test-file-directory: "release-branches"
      test-suite: "incentivized-transfer"
