name: Goimports
on: pull_request
jobs:
  goimports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Go Imports"
        run: .github/scripts/go-imports.sh
