name: Check Markdown links
on: [push, pull_request]
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/link-check-config.json'
  goimports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Go Imports"
        run: |
          docker run  -v "$(pwd)":/ibc-go --rm  -w "/ibc-go" --entrypoint="" cytopia/goimports  /ibc-go/.github/scripts/go-imports.sh
